import test from "node:test";
import assert from "node:assert/strict";
import { mkdtempSync, mkdirSync, cpSync, writeFileSync, readFileSync, rmSync } from "node:fs";
import { tmpdir } from "node:os";
import { join, resolve } from "node:path";
import { execFileSync, spawnSync } from "node:child_process";
import { hash } from "../scripts/publication-lib.mjs";

test("derivative publication preserves verified source, identity and license materials", t => {
  const root = mkdtempSync(join(tmpdir(), "market-derivative-drill-"));
  t.after(() => rmSync(root, { recursive: true, force: true }));
  const put = (path, value) => { mkdirSync(join(root, path, ".."), { recursive: true }); writeFileSync(join(root, path), value); };
  const git = (...args) => execFileSync("git", args, { cwd: root, encoding: "utf8", stdio: ["ignore", "pipe", "pipe"] }).trim();
  cpSync(resolve("scripts"), join(root, "scripts"), { recursive: true });
  const source = { notchany_export: 2, action: { id: "notchany.custom.shell.source", name: "Source", kind: "shell", input_kind: "none", script: "true" } };
  const manifest = { manifest_version: 1, names: { en: "Example" }, summaries: { en: "Example" }, version: "1.0.0", license: "MIT" };
  const sourceBytes = JSON.stringify(source);
  const icon = readFileSync(resolve("packages/glzlaohuai/metric-template/icon.png"));
  const license = "MIT License\nCopyright (c) Test fixture authors\n";
  put("packages/alice/source/package.notchany.json", sourceBytes);
  put("packages/alice/source/manifest.json", JSON.stringify(manifest));
  put("packages/alice/source/icon.png", icon);
  put("packages/alice/source/LICENSE", license);
  git("init", "-b", "main"); git("config", "user.name", "Test"); git("config", "user.email", "test@example.com");
  git("add", "."); git("commit", "-m", "verified source");
  const commit = git("rev-parse", "HEAD");
  put("history/v1/alice/source.json", JSON.stringify({ history_schema: 1, package_id: "alice/source",
    releases: [{ version: "1.0.0", sha256: hash(sourceBytes), source_commit: commit, pr: null, merged_at: null, contributors: [] }], contributors: [] }));
  const derived = structuredClone(source);
  derived.action.id = "notchany.custom.shell.derivative";
  derived.action.script = "echo derivative";
  const target = { ...manifest, derived_from: { package_id: "alice/source", version: "1.0.0", sha256: hash(sourceBytes) } };
  const save = () => { put("packages/bob/derivative/package.notchany.json", JSON.stringify(derived)); put("packages/bob/derivative/manifest.json", JSON.stringify(target)); };
  put("packages/bob/derivative/LICENSE", license);
  put("packages/bob/derivative/icon.png", icon);
  const check = () => spawnSync(process.execPath, ["scripts/check-pr.mjs"], { cwd: root, encoding: "utf8", env: { ...process.env, SKIP_MARKET_AUTH: "1" } });
  save();
  const valid = check();
  assert.equal(valid.status, 0, valid.stdout + valid.stderr);
  derived.action.id = source.action.id; save();
  assert.notEqual(check().status, 0);
  derived.action.id = "notchany.custom.shell.derivative"; save();
  rmSync(join(root, "packages/bob/derivative/LICENSE"));
  assert.notEqual(check().status, 0);
  put("packages/bob/derivative/LICENSE", license);
  target.derived_from.sha256 = "0".repeat(64); save();
  assert.notEqual(check().status, 0);
  target.derived_from.sha256 = hash(sourceBytes); target.license = "Unlicense"; save();
  assert.notEqual(check().status, 0);
});
