import test from "node:test";
import assert from "node:assert/strict";
import { mkdtempSync, mkdirSync, cpSync, writeFileSync, readFileSync, rmSync, existsSync } from "node:fs";
import { tmpdir } from "node:os";
import { join, resolve } from "node:path";
import { execFileSync, spawnSync } from "node:child_process";
import { hash, treeHash } from "../scripts/publication-lib.mjs";

test("publication rehearsal: rejection preserves baseline, revoked review blocks merge, retry publishes the exact batch", { timeout: 120000 }, t => {
  const root = mkdtempSync(join(tmpdir(), "market-release-drill-"));
  t.after(() => rmSync(root, { recursive: true, force: true }));
  const repo = join(root, "repo");
  mkdirSync(repo);
  const put = (path, value) => { mkdirSync(join(repo, path, ".."), { recursive: true }); writeFileSync(join(repo, path), value); };
  const git = (...args) => execFileSync("git", args, { cwd: repo, encoding: "utf8", stdio: ["ignore", "pipe", "pipe"] }).trim();
  cpSync(resolve("scripts"), join(repo, "scripts"), { recursive: true });
  const packageID = "alice/example";
  const action = JSON.stringify({ notchany_export: 2, action: { id: "notchany.custom.shell.test", name: "Example", kind: "shell", input_kind: "none", script: "echo original" } });
  const files = { "package.notchany.json": Buffer.from(action), "manifest.json": Buffer.from(JSON.stringify({ manifest_version: 1, names: { en: "Example" }, summaries: { en: "Example" }, version: "1.0.0", license: "MIT" })),
    "icon.png": readFileSync(resolve("packages/glzlaohuai/metric-template/icon.png")) };
  for (const [path, bytes] of Object.entries(files)) put(`packages/${packageID}/${path}`, bytes);
  git("init", "-b", "main"); git("config", "user.name", "Test"); git("config", "user.email", "test@example.com"); git("add", "."); git("commit", "-m", "source");
  const source = git("rev-parse", "HEAD");
  const release = { version: "1.0.0", sha256: hash(action), source_commit: source, merged_at: null, pr: null, contributors: [] };
  for (const [path, bytes] of Object.entries(files)) put(`published/${packageID}/${path}`, bytes);
  put("published/state.json", JSON.stringify({ schema: 1, packages: { [packageID]: { active: true, source_commit: source, tree_hash: treeHash(files), release } }, decisions: [] }));
  put(`history/v1/${packageID}.json`, JSON.stringify({ history_schema: 1, package_id: packageID, releases: [release], contributors: [] }));
  execFileSync(process.execPath, ["scripts/build-index.mjs"], { cwd: repo });
  git("add", "."); git("commit", "-m", "published baseline");
  const oldIndex = readFileSync(join(repo, "index/v1/index.json"), "utf8");
  put(`packages/${packageID}/package.notchany.json`, action.replace("echo original", "echo updated"));
  put(`packages/${packageID}/manifest.json`, files["manifest.json"].toString().replace("1.0.0", "1.1.0"));
  git("add", "."); git("commit", "-m", "reviewed update");
  const candidate = git("rev-parse", "HEAD");
  git("init", "--bare", join(root, "origin.git"));
  git("remote", "add", "origin", join(root, "origin.git"));
  git("push", "origin", "main", `${candidate}:refs/pull/42/head`);
  const statePath = join(root, "api-state.json");
  const logPath = join(root, "api-log.jsonl");
  const state = { candidate, head: "", revoked: true, packageID };
  const save = () => writeFileSync(statePath, JSON.stringify(state));
  save();
  const preload = join(root, "fetch.mjs");
  writeFileSync(preload, `
    import {readFileSync,appendFileSync} from "node:fs";
    import {createHmac} from "node:crypto";
    const profile = {id: 100,login:"alice"};
    globalThis.fetch = async (url, options = {}) => {
      const s=JSON.parse(readFileSync(process.env.DRILL_STATE)); const path=new URL(url).pathname;
      const body=options.body ? JSON.parse(options.body) : {};
      appendFileSync(process.env.DRILL_LOG, JSON.stringify({path,body})+"\\n");
      if(path.startsWith("/internal/")) {
        const signature=createHmac("sha256","drill-secret").update(options.headers["X-NotchAny-Timestamp"]+"."+options.body).digest("hex");
        if(signature!==options.headers["X-NotchAny-Signature"]) throw Error("signature");
        const decision={allowed:!s.revoked,reason:s.revoked?"review_required":"reviewed_contribution",policy_revision:1,approved_by:[{github_user_id:"100",review_id:"10"}]};
        if(path.endsWith("pr-evaluate")) return Response.json(decision);
        if(s.revoked) return Response.json({code:"market_forbidden"},{status:403});
        if(path.endsWith("publication-prepare")) return Response.json({decision_id:"00000000-0000-0000-0000-000000000001",decisions:[decision]});
        return Response.json({ok:true});
      }
      if(path.endsWith("/dispatches")) return new Response(null,{status:204});
      if(path.includes("/statuses/")) return Response.json({});
      if(path.endsWith("/merge")) return Response.json({merged:true,sha:s.head});
      const pr=n=>({number:n,state:n===42?"closed":"open",merged_at:n===42?"2026-09-13T00:00:00Z":null,head:{sha:n===42?s.candidate:s.head,ref:n===42?"source":"codex/publish-drill",repo:{full_name:"glzlaohuai/notchany-registry"}},base:{ref:"main",sha:s.candidate,repo:{full_name:"glzlaohuai/notchany-registry"}},user:{id:101,login:"contributor"},changed_files:2,commits:1,title:"Update",html_url:"https://github.com/glzlaohuai/notchany-registry/pull/"+n});
      if(/\\/commits\\/[^/]+\\/pulls$/.test(path)) return Response.json([pr(42)]);
      if(path.endsWith("/pulls/42/files")) return Response.json(["manifest.json","package.notchany.json"].map(name=>({filename:"packages/"+s.packageID+"/"+name,status:"modified"})));
      if(path.endsWith("/pulls/42/reviews")) return Response.json(s.revoked?[]:[{id:10,user:profile,commit_id:s.candidate,state:"APPROVED",submitted_at:"2026-09-13T00:00:00Z"}]);
      if(path.endsWith("/pulls/42/commits")) return Response.json([{author:profile}]);
      if(path.endsWith("/pulls/42")) return Response.json(pr(42));
      if(path.endsWith("/pulls/99")) return Response.json(pr(99));
      throw Error("Unexpected request "+path);
    };
  `);
  const env = { ...process.env, NODE_OPTIONS: `--import=${preload}`, MARKET_API_BASE: "https://market.test", MARKET_INTERNAL_HMAC_SECRET: "drill-secret",
    GITHUB_TOKEN: "drill-token", DRILL_STATE: statePath, DRILL_LOG: logPath, PR_NUMBER: "99", MERGE_PUBLICATION: "1" };
  const run = file => spawnSync(process.execPath, [`scripts/${file}`], { cwd: repo, env, encoding: "utf8" });
  assert.notEqual(run("publish-approved.mjs").status, 0);
  assert.equal(readFileSync(join(repo, "index/v1/index.json"), "utf8"), oldIndex);
  assert.equal(existsSync(join(repo, "publication/last-batch.json")), false);
  state.revoked = false; save();
  const published = run("publish-approved.mjs");
  assert.equal(published.status, 0, published.stderr);
  git("switch", "-c", "codex/publish-drill"); git("add", "."); git("commit", "-m", "generated release");
  state.head = git("rev-parse", "HEAD"); save();
  git("push", "origin", `${state.head}:refs/pull/99/head`);
  state.revoked = true; save();
  assert.notEqual(run("validate-publication.mjs").status, 0);
  assert.ok(!readFileSync(logPath, "utf8").includes('"path":"/repos/glzlaohuai/notchany-registry/pulls/99/merge"'));
  state.revoked = false; save();
  const retry = run("validate-publication.mjs");
  assert.equal(retry.status, 0, retry.stderr);
  const log = readFileSync(logPath, "utf8").trim().split("\n").map(JSON.parse);
  assert.equal(log.filter(entry => entry.path.endsWith("/merge")).length, 1);
  assert.ok(log.some(entry => entry.path.endsWith("/publication-complete")));
  assert.ok(log.some(entry => entry.path.endsWith("/deploy-pages.yml/dispatches")));
  const index = JSON.parse(readFileSync(join(repo, "index/v1/index.json")));
  assert.equal(index.packages[0].version, "1.1.0");
  assert.equal(index.packages[0].path, "published/alice/example/package.notchany.json");
});
